org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2,TLSv1.3
org.gradle.parallel=true
org.gradle.caching=true
kotlin.daemon.jvmargs=-Xmx2G
kotlin.compiler.execution.strategy=in-process

minecraft_version=1.20.1

# Mod Properties
maven_group=com.yuan
mod_id=yuan

# Dependencies
forge_version=47.4.20

# 运行游戏时的人物名称
minecraft_username=Developer
